[package]
name = "dig-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = { version = "2.13.0", features = ["chrono-0_4"] }
chrono = "0.4.38"
mongodb = "3.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.132"
strum = "0.26.3"
strum_macros = "0.26.4"
